// Curated emoji set for the group-icon picker — the common, useful ones with
// search keywords, grouped by category. Not the full ~1900 Unicode set: this is
// hand-picked for "label a folder", and the picker reads it generically so a
// fuller dataset can drop in later without touching emojiPicker.js.
//
// Each entry: [char, name, "space separated keywords"]. Publishes a global.

(function (root) {
  const CATEGORIES = [
    {
      id: "smileys",
      label: "Smileys",
      emoji: [
        ["😀", "grinning", "smile happy face"],
        ["😄", "laughing", "smile happy joy"],
        ["😁", "beaming", "smile grin"],
        ["🙂", "slight smile", "happy"],
        ["😉", "wink", "flirt"],
        ["😍", "heart eyes", "love adore"],
        ["😎", "cool", "sunglasses awesome"],
        ["🤩", "star struck", "excited amazed"],
        ["🥳", "party face", "celebrate birthday"],
        ["😷", "masked", "sick mask ill"],
        ["🤒", "sick", "thermometer fever ill"],
        ["🤔", "thinking", "hmm consider"],
        ["🤨", "raised eyebrow", "skeptical suspicious"],
        ["😴", "sleeping", "tired zzz bored"],
        ["😭", "crying", "sad sob tears"],
        ["😡", "angry", "mad rage"],
        ["🤯", "mind blown", "shocked wow"],
        ["🥺", "pleading", "puppy eyes"],
        ["🤫", "shushing", "quiet secret"],
        ["🤓", "nerd", "geek smart glasses"],
        ["😈", "smiling devil", "evil mischief"],
        ["👻", "ghost", "halloween spooky boo"],
        ["💀", "skull", "dead death"],
        ["🤖", "robot", "bot ai machine"],
        ["👽", "alien", "ufo space"],
        ["🎃", "jack-o-lantern", "halloween pumpkin"],
        ["😺", "grinning cat", "smile"],
        ["😻", "heart eyes cat", "love"],
        ["🙈", "see no evil", "monkey hide"],
        ["💩", "poop", "crap"],
      ],
    },
    {
      id: "people",
      label: "People",
      emoji: [
        ["👋", "wave", "hi bye hello"],
        ["👍", "thumbs up", "like yes approve"],
        ["👎", "thumbs down", "dislike no"],
        ["👏", "clap", "applause bravo"],
        ["🙏", "folded hands", "thanks please pray"],
        ["💪", "flexed biceps", "strong muscle gym"],
        ["🧠", "brain", "smart think mind"],
        ["👀", "eyes", "look watch see"],
        ["🗣️", "speaking head", "talk voice"],
        ["👶", "baby", "infant child"],
        ["🧑", "person", "adult"],
        ["👨", "man", "male"],
        ["👩", "woman", "female"],
        ["👴", "old man", "grandpa elder"],
        ["👮", "police", "cop officer"],
        ["🕵️", "detective", "spy investigate"],
        ["👷", "construction worker", "builder"],
        ["🧑‍🍳", "cook", "chef kitchen"],
        ["🧑‍🎓", "student", "graduate school"],
        ["🧑‍🏫", "teacher", "professor lecture"],
        ["🧑‍💻", "technologist", "programmer developer coder"],
        ["🧑‍🎤", "singer", "musician performer"],
        ["🧑‍🚀", "astronaut", "space nasa"],
        ["🧑‍⚕️", "health worker", "doctor nurse medical"],
        ["🦸", "superhero", "hero"],
        ["🧙", "mage", "wizard magic fantasy"],
        ["🥷", "ninja", "stealth"],
        ["🤺", "fencer", "fencing sport"],
        ["🏃", "running", "run exercise"],
        ["🧘", "meditation", "yoga calm zen"],
        ["👨‍👩‍👧", "family", "parents kids"],
      ],
    },
    {
      id: "animals",
      label: "Animals & Nature",
      emoji: [
        ["🐶", "dog", "puppy pet"],
        ["🐱", "cat", "kitten pet"],
        ["🐭", "mouse", "rodent"],
        ["🐰", "rabbit", "bunny"],
        ["🦊", "fox", ""],
        ["🐻", "bear", ""],
        ["🐼", "panda", ""],
        ["🐨", "koala", ""],
        ["🦁", "lion", "king"],
        ["🐯", "tiger", ""],
        ["🐮", "cow", "cattle"],
        ["🐷", "pig", ""],
        ["🐸", "frog", "toad"],
        ["🐵", "monkey", "ape"],
        ["🦄", "unicorn", "fantasy magic"],
        ["🐔", "chicken", "hen"],
        ["🐧", "penguin", ""],
        ["🐦", "bird", ""],
        ["🦅", "eagle", "bird"],
        ["🦉", "owl", "bird night wise"],
        ["🐺", "wolf", ""],
        ["🐗", "boar", "pig"],
        ["🐴", "horse", "pony"],
        ["🦇", "bat", "vampire"],
        ["🐝", "bee", "honey"],
        ["🐛", "bug", "insect caterpillar"],
        ["🦋", "butterfly", "insect"],
        ["🐌", "snail", "slow"],
        ["🐙", "octopus", "sea"],
        ["🦑", "squid", "sea"],
        ["🦀", "crab", "sea"],
        ["🐠", "fish", "tropical sea aquarium"],
        ["🐬", "dolphin", "sea"],
        ["🐳", "whale", "sea ocean"],
        ["🐊", "crocodile", "alligator reptile"],
        ["🐍", "snake", "reptile"],
        ["🐢", "turtle", "tortoise slow"],
        ["🦖", "t-rex", "dinosaur"],
        ["🌵", "cactus", "desert plant"],
        ["🌲", "evergreen tree", "forest pine"],
        ["🌴", "palm tree", "tropical beach"],
        ["🌿", "herb", "leaf plant green"],
        ["🍀", "four leaf clover", "luck"],
        ["🌸", "cherry blossom", "flower spring"],
        ["🌹", "rose", "flower love"],
        ["🌻", "sunflower", "flower"],
        ["🌍", "earth", "world globe planet"],
        ["🌙", "crescent moon", "night"],
        ["⭐", "star", "favorite"],
        ["🔥", "fire", "flame hot lit trending"],
        ["⚡", "lightning", "bolt electric power fast"],
        ["🌈", "rainbow", "pride colors"],
        ["💧", "droplet", "water rain"],
        ["🌊", "wave", "ocean sea water"],
        ["❄️", "snowflake", "winter cold snow"],
      ],
    },
    {
      id: "food",
      label: "Food & Drink",
      emoji: [
        ["🍏", "green apple", "fruit"],
        ["🍎", "red apple", "fruit"],
        ["🍊", "orange", "fruit tangerine"],
        ["🍋", "lemon", "fruit sour"],
        ["🍌", "banana", "fruit"],
        ["🍉", "watermelon", "fruit summer"],
        ["🍇", "grapes", "fruit wine"],
        ["🍓", "strawberry", "fruit berry"],
        ["🫐", "blueberries", "fruit berry"],
        ["🍒", "cherries", "fruit"],
        ["🍑", "peach", "fruit"],
        ["🥭", "mango", "fruit tropical"],
        ["🍍", "pineapple", "fruit tropical"],
        ["🥥", "coconut", "tropical"],
        ["🥑", "avocado", "fruit"],
        ["🍅", "tomato", "vegetable"],
        ["🌶️", "hot pepper", "spicy chili"],
        ["🌽", "corn", "vegetable"],
        ["🥕", "carrot", "vegetable"],
        ["🥔", "potato", "vegetable"],
        ["🍞", "bread", "loaf"],
        ["🧀", "cheese", "dairy"],
        ["🥚", "egg", ""],
        ["🍳", "cooking", "fried egg breakfast kitchen"],
        ["🥓", "bacon", "meat breakfast"],
        ["🍔", "burger", "hamburger fast food"],
        ["🍟", "fries", "chips fast food"],
        ["🍕", "pizza", "italian fast food"],
        ["🌭", "hot dog", "sausage"],
        ["🌮", "taco", "mexican"],
        ["🌯", "burrito", "mexican wrap"],
        ["🍜", "noodles", "ramen soup asian"],
        ["🍣", "sushi", "japanese fish"],
        ["🍰", "cake", "dessert birthday"],
        ["🎂", "birthday cake", "celebrate"],
        ["🍪", "cookie", "dessert biscuit"],
        ["🍫", "chocolate", "dessert candy"],
        ["🍩", "donut", "doughnut dessert"],
        ["🍦", "ice cream", "dessert cold"],
        ["🍿", "popcorn", "movie cinema snack"],
        ["☕", "coffee", "hot drink cafe"],
        ["🍵", "tea", "hot drink"],
        ["🧃", "juice box", "drink"],
        ["🥤", "soda", "drink cup soft"],
        ["🍺", "beer", "drink alcohol"],
        ["🍷", "wine", "drink alcohol"],
        ["🥂", "champagne", "toast celebrate"],
        ["🍸", "cocktail", "drink alcohol bar"],
      ],
    },
    {
      id: "activities",
      label: "Activities",
      emoji: [
        ["⚽", "soccer", "football sport ball"],
        ["🏀", "basketball", "sport ball"],
        ["🏈", "american football", "sport"],
        ["⚾", "baseball", "sport"],
        ["🎾", "tennis", "sport"],
        ["🏐", "volleyball", "sport"],
        ["🏉", "rugby", "sport"],
        ["🎱", "billiards", "pool 8 ball"],
        ["🏓", "ping pong", "table tennis sport"],
        ["🏸", "badminton", "sport"],
        ["🥊", "boxing", "gloves fight sport"],
        ["🥋", "martial arts", "karate judo"],
        ["⛳", "golf", "sport flag"],
        ["🏌️", "golfer", "golf sport"],
        ["🎿", "skis", "ski winter sport"],
        ["🏂", "snowboard", "winter sport"],
        ["🏄", "surfing", "surf sport wave"],
        ["🚴", "cycling", "bike bicycle sport"],
        ["🏋️", "weightlifting", "gym fitness sport"],
        ["🤸", "gymnastics", "cartwheel sport"],
        ["🏆", "trophy", "win award champion"],
        ["🥇", "gold medal", "win first"],
        ["🎖️", "medal", "award military"],
        ["🎮", "video game", "gaming controller gamepad"],
        ["🕹️", "joystick", "arcade gaming retro"],
        ["🎲", "dice", "board game random"],
        ["♟️", "chess", "pawn strategy"],
        ["🧩", "puzzle", "jigsaw piece"],
        ["🎯", "dartboard", "target aim bullseye"],
        ["🎰", "slot machine", "gambling casino"],
        ["🎨", "artist palette", "art paint draw"],
        ["🖌️", "paintbrush", "art paint"],
        ["✏️", "pencil", "write draw edit"],
        ["🎭", "performing arts", "theater drama masks"],
        ["🎬", "clapper", "movie film cinema director"],
        ["🎤", "microphone", "sing karaoke podcast"],
        ["🎧", "headphones", "music audio listen"],
        ["🎵", "musical note", "music song"],
        ["🎶", "musical notes", "music song melody"],
        ["🎹", "piano", "keyboard music"],
        ["🎸", "guitar", "music rock"],
        ["🥁", "drum", "music percussion"],
        ["🎺", "trumpet", "music brass jazz"],
        ["🎻", "violin", "music classical strings"],
        ["🎼", "musical score", "sheet music"],
        ["🎪", "circus tent", "show carnival"],
        ["🎉", "party popper", "celebrate confetti"],
        ["🎊", "confetti ball", "celebrate party"],
        ["🎈", "balloon", "party celebrate"],
        ["🎁", "gift", "present box"],
        ["🎟️", "ticket", "admission event"],
        ["🏅", "sports medal", "award"],
      ],
    },
    {
      id: "travel",
      label: "Travel & Places",
      emoji: [
        ["🚗", "car", "auto vehicle drive"],
        ["🚕", "taxi", "cab car"],
        ["🚙", "suv", "car vehicle"],
        ["🏎️", "race car", "racing formula speed"],
        ["🚓", "police car", "cop"],
        ["🚑", "ambulance", "medical emergency"],
        ["🚒", "fire truck", "emergency"],
        ["🚚", "truck", "delivery lorry"],
        ["🚜", "tractor", "farm"],
        ["🏍️", "motorcycle", "bike moto"],
        ["🚲", "bicycle", "bike cycle"],
        ["🛴", "scooter", "kick"],
        ["🚌", "bus", "transit"],
        ["🚂", "locomotive", "train steam"],
        ["🚆", "train", "rail metro"],
        ["🚀", "rocket", "space launch startup"],
        ["🛸", "flying saucer", "ufo alien"],
        ["✈️", "airplane", "flight travel plane"],
        ["🚁", "helicopter", "chopper"],
        ["⛵", "sailboat", "boat sea"],
        ["🚢", "ship", "cruise boat sea"],
        ["🚤", "speedboat", "boat"],
        ["⚓", "anchor", "ship navy sea"],
        ["🗺️", "world map", "travel geography"],
        ["🧭", "compass", "navigation direction"],
        ["🏔️", "mountain", "snow peak"],
        ["🏕️", "camping", "tent outdoors"],
        ["🏖️", "beach", "sand vacation"],
        ["🏝️", "desert island", "tropical"],
        ["🌋", "volcano", "eruption lava"],
        ["🏙️", "cityscape", "city skyline urban"],
        ["🏛️", "classical building", "museum government bank"],
        ["🏰", "castle", "fortress medieval"],
        ["🗼", "tower", "landmark"],
        ["🎡", "ferris wheel", "amusement park fair"],
        ["🎢", "roller coaster", "amusement park"],
        ["🗽", "statue of liberty", "new york usa"],
        ["🏠", "house", "home"],
        ["🏢", "office building", "work company"],
        ["🏭", "factory", "industry manufacturing"],
        ["🏥", "hospital", "medical"],
        ["🏦", "bank", "money finance"],
        ["🏨", "hotel", "travel stay"],
        ["🏫", "school", "education"],
        ["⛪", "church", "religion"],
        ["🌃", "night city", "stars skyline"],
      ],
    },
    {
      id: "objects",
      label: "Objects",
      emoji: [
        ["⌚", "watch", "time wrist"],
        ["📱", "phone", "mobile smartphone cell"],
        ["💻", "laptop", "computer pc coding"],
        ["🖥️", "desktop", "computer monitor pc"],
        ["🖨️", "printer", "print"],
        ["⌨️", "keyboard", "typing computer"],
        ["🖱️", "mouse", "computer click"],
        ["💽", "minidisc", "storage"],
        ["💾", "floppy disk", "save storage"],
        ["💿", "cd", "disc storage"],
        ["📀", "dvd", "disc video"],
        ["📷", "camera", "photo photography"],
        ["📸", "camera flash", "photo photography"],
        ["📹", "video camera", "record film"],
        ["🎥", "movie camera", "film cinema"],
        ["📽️", "film projector", "movie cinema"],
        ["🎞️", "film frames", "movie cinema"],
        ["📺", "television", "tv screen show"],
        ["📻", "radio", "broadcast music"],
        ["🎙️", "studio microphone", "podcast recording"],
        ["🎚️", "level slider", "audio mixer"],
        ["🎛️", "control knobs", "audio mixer dj"],
        ["⏱️", "stopwatch", "timer speed"],
        ["⏲️", "timer", "clock countdown"],
        ["⏰", "alarm clock", "time wake"],
        ["🔋", "battery", "power charge"],
        ["🔌", "plug", "power electric"],
        ["💡", "light bulb", "idea invention"],
        ["🔦", "flashlight", "torch light"],
        ["🕯️", "candle", "light flame"],
        ["📕", "closed book", "read"],
        ["📗", "green book", "read"],
        ["📘", "blue book", "read"],
        ["📚", "books", "library read study education"],
        ["📖", "open book", "read story"],
        ["📓", "notebook", "notes"],
        ["📰", "newspaper", "news press article"],
        ["🗞️", "rolled newspaper", "news"],
        ["📄", "page", "document file"],
        ["📁", "folder", "files organize"],
        ["📂", "open folder", "files"],
        ["🗂️", "card index dividers", "organize tabs"],
        ["📊", "bar chart", "stats data analytics"],
        ["📈", "chart up", "growth stocks trending"],
        ["📉", "chart down", "decline loss"],
        ["📌", "pushpin", "pin location"],
        ["📎", "paperclip", "attach"],
        ["✂️", "scissors", "cut"],
        ["🔍", "magnifying glass", "search find zoom"],
        ["🔑", "key", "unlock password"],
        ["🔒", "locked", "secure private"],
        ["🔓", "unlocked", "open"],
        ["🔨", "hammer", "build tool fix"],
        ["🪛", "screwdriver", "tool fix"],
        ["🔧", "wrench", "tool fix settings"],
        ["⚙️", "gear", "settings config machine"],
        ["🧰", "toolbox", "tools repair"],
        ["🧪", "test tube", "science lab experiment chemistry"],
        ["🔬", "microscope", "science lab biology research"],
        ["🔭", "telescope", "astronomy space stars"],
        ["🧲", "magnet", "attract physics"],
        ["💊", "pill", "medicine drug health"],
        ["💉", "syringe", "vaccine medical shot"],
        ["🩺", "stethoscope", "doctor medical health"],
        ["🌡️", "thermometer", "temperature fever"],
        ["💰", "money bag", "cash rich wealth"],
        ["💵", "dollar", "money cash bill"],
        ["💳", "credit card", "payment money"],
        ["💎", "gem", "diamond jewel premium"],
        ["🛒", "shopping cart", "buy store retail"],
        ["🎓", "graduation cap", "school degree education"],
        ["🧳", "luggage", "travel suitcase"],
        ["🧵", "thread", "sewing craft"],
        ["🧶", "yarn", "knit craft"],
      ],
    },
    {
      id: "symbols",
      label: "Symbols",
      emoji: [
        ["❤️", "red heart", "love like"],
        ["🧡", "orange heart", "love"],
        ["💛", "yellow heart", "love"],
        ["💚", "green heart", "love"],
        ["💙", "blue heart", "love"],
        ["💜", "purple heart", "love"],
        ["🖤", "black heart", "love dark"],
        ["🤍", "white heart", "love"],
        ["💖", "sparkling heart", "love"],
        ["💯", "hundred", "perfect score 100"],
        ["✅", "check mark", "done yes complete ok"],
        ["❌", "cross mark", "no wrong error delete"],
        ["⭕", "circle", "correct"],
        ["❓", "question", "help ask"],
        ["❗", "exclamation", "warning important"],
        ["⚠️", "warning", "caution danger"],
        ["🚫", "prohibited", "no forbidden block ban"],
        ["♻️", "recycle", "reuse green"],
        ["🔞", "no under 18", "adult mature nsfw"],
        ["✳️", "eight spoked asterisk", "star"],
        ["✴️", "eight pointed star", "sparkle"],
        ["🆕", "new", "fresh"],
        ["🆓", "free", "no cost"],
        ["🆒", "cool", ""],
        ["🔝", "top", "up best"],
        ["🔤", "abc", "letters alphabet text"],
        ["🔢", "numbers", "1234 digits"],
        ["#️⃣", "hash", "number pound tag"],
        ["▶️", "play", "start video"],
        ["⏸️", "pause", "stop"],
        ["⏭️", "next track", "skip forward"],
        ["🔀", "shuffle", "random"],
        ["🔁", "repeat", "loop"],
        ["🔊", "speaker loud", "volume sound audio"],
        ["🔇", "muted", "silent volume off"],
        ["🔔", "bell", "notification alert reminder"],
        ["🔕", "no bell", "mute notification"],
        ["📢", "loudspeaker", "announce broadcast"],
        ["💬", "speech bubble", "chat comment message"],
        ["💭", "thought bubble", "think idea"],
        ["🗯️", "anger bubble", "rage shout"],
        ["♠️", "spades", "card suit"],
        ["♥️", "hearts", "card suit"],
        ["♦️", "diamonds", "card suit"],
        ["♣️", "clubs", "card suit"],
        ["🃏", "joker", "card wild"],
        ["🀄", "mahjong", "tile game"],
        ["✨", "sparkles", "shiny magic new"],
        ["🌟", "glowing star", "favorite special"],
        ["💫", "dizzy", "star sparkle"],
        ["🏳️", "white flag", "surrender"],
        ["🏴", "black flag", ""],
        ["🏁", "chequered flag", "race finish start"],
        ["🚩", "triangular flag", "marker milestone"],
      ],
    },
  ];

  root.YSTEmojiData = CATEGORIES;
  if (typeof module !== "undefined" && module.exports) module.exports = CATEGORIES;
})(typeof window !== "undefined" ? window : globalThis);
